spring:
  session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
